### ISSUE TITLE
Tried to use it in my personal account, but didn't see any change on the records list

### ISSUE THREAD

**Issue by diasdavid** [ipfs/dnslink-deploy#5]
@RichardLitt @lgierth can you confirm this tool is working? It didn't throw any error, but also didn't see a change on DO dns list

**Comment by lgierth** [comment]
It does work for me, but it doesn't properly fail if the record you're trying to change doesn't exist. It should probably update-or-create?

**Comment by diasdavid** [comment]
Ah, didn't realize this was looking to just update to previous created records. Yes, update-or-create would be nice :)

**Comment by jbenet** [comment]
I know it's working because i hosed, and then fixed, the website with it. :D :dancer: (my fault, should've verified the record before using it. maybe we should have a test before it publishes it, like curling a well-known URL that _should_ work at the hash before pushing it out)

**Comment by diasdavid** [comment]
solid!  :)

currently hosting my page successfully using ipsurge tooling http://ipfs.daviddias.me/ :D

**Comment by jbenet** [comment]
:clap: :clap:
